[package]
name = "onisync"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "onisync"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
comfy-table = { workspace = true }
owo-colors = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
onisyncd = { workspace = true }
onisync-core = { workspace = true }
tokio = { workspace = true, features = ["full"] }
